version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: councilors
  - name: bronze_311
    tables:
      - name: service_requests

models:
  - name: stg_councilors
    description: "Staged Somerville Councilor data"
    meta:
      lightdash:
        show_as_table: true
    tags: ["lightdash"]
    columns:
      - name: councilor_id
        tests:
          - unique
          - not_null
      - name: councilor_ward
        tests:
          - not_null
