name: 'refinery'
version: '1.0.0'
config-version: 2

profile: 'refinery'

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  warehouse_path: "gs://warehouse-011793-factory"

on-run-start:
  - "{{ setup_gcs() }}"

models:
  refinery:
    staging:
      +materialized: view

dispatch:
  - macro_namespace: dbt_profiler
    search_order: ['refinery', 'dbt_profiler']

