name: 'refinery'
version: '1.0.0'
config-version: 2

profile: 'refinery'

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  refinery:
    staging:
      +materialized: view
